"use client";

import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, ArrowUpDown, Search, SlidersHorizontal } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export type DataTableColumn<T> = { id: string; header: string; cell: (row: T) => React.ReactNode; sortValue?: (row: T) => string | number | null };

export function DataTable<T>({ data, columns, searchPlaceholder = "Buscar...", searchValue, emptyMessage = "Nenhum registro encontrado." }: { data: T[]; columns: DataTableColumn<T>[]; searchPlaceholder?: string; searchValue?: (row: T) => string; emptyMessage?: string }) {
  const [query, setQuery] = useState(""); const [sort, setSort] = useState<{ id: string; direction: "asc" | "desc" } | null>(null); const [pageSize, setPageSize] = useState(30); const [page, setPage] = useState(1); const [showFilters, setShowFilters] = useState(false);
  const filtered = useMemo(() => data.filter((row) => (searchValue ? searchValue(row) : Object.values(row as Record<string, unknown>).join(" ")).toLowerCase().includes(query.toLowerCase())), [data, query, searchValue]);
  const sorted = useMemo(() => { if (!sort) return filtered; const column = columns.find((item) => item.id === sort.id); if (!column?.sortValue) return filtered; return [...filtered].sort((left, right) => { const a = column.sortValue?.(left) ?? ""; const b = column.sortValue?.(right) ?? ""; return (a < b ? -1 : a > b ? 1 : 0) * (sort.direction === "asc" ? 1 : -1); }); }, [columns, filtered, sort]);
  const totalPages = Math.max(1, Math.ceil(sorted.length / pageSize)); const currentPage = Math.min(page, totalPages); const visible = sorted.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  function sortBy(column: DataTableColumn<T>) { if (!column.sortValue) return; setPage(1); setSort((current) => !current || current.id !== column.id ? { id: column.id, direction: "asc" } : current.direction === "asc" ? { id: column.id, direction: "desc" } : null); }
  return <Card className="w-full overflow-hidden"><CardContent className="flex min-h-0 flex-col gap-4 p-4"><div className="flex shrink-0 flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full lg:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input type="search" placeholder={searchPlaceholder} value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} className="pl-9" /></div><Button variant={showFilters ? "default" : "outline"} size="sm" onClick={() => setShowFilters((value) => !value)}><SlidersHorizontal className="mr-2 size-4" />+ Filtros</Button></div>{showFilters && <div className="rounded-sm border bg-muted/30 px-3 py-2 text-xs text-muted-foreground">Use a busca acima para filtrar por nome, Client ID ou permissão.</div>}<div className="min-h-0 flex-1 overflow-auto rounded-sm border"><Table><TableHeader><TableRow className="bg-muted/50 hover:bg-muted/50">{columns.map((column) => <TableHead key={column.id} className={column.id === "actions" ? "w-px whitespace-nowrap" : "compact"}>{column.sortValue ? <button onClick={() => sortBy(column)} className="flex items-center gap-1 font-medium">{column.header}{sort?.id === column.id ? sort.direction === "asc" ? <ArrowUp className="size-4" /> : <ArrowDown className="size-4" /> : <ArrowUpDown className="size-4 opacity-40" />}</button> : column.header}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map((row, index) => <TableRow key={index} className="compact text-sm">{columns.map((column) => <TableCell key={column.id} className={column.id === "actions" ? "w-px whitespace-nowrap !px-2 !py-1.5" : "!px-2 !py-1.5"}>{column.cell(row)}</TableCell>)}</TableRow>)}{!visible.length && <TableRow><TableCell colSpan={columns.length} className="h-24 text-center">{emptyMessage}</TableCell></TableRow>}</TableBody></Table></div><div className="flex flex-col gap-3 px-1 text-sm text-muted-foreground lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-2"><span>Exibindo</span><select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }} className="h-8 rounded-sm border border-input bg-background px-2 text-sm"><option value={10}>10</option><option value={30}>30</option><option value={50}>50</option><option value={100}>100</option></select><span>de {sorted.length} registro(s)</span></div>{totalPages > 1 && <div className="flex flex-wrap items-center gap-1"><Button variant="outline" size="sm" onClick={() => setPage(1)} disabled={currentPage === 1}>Primeira</Button><Button variant="outline" size="sm" onClick={() => setPage((value) => value - 1)} disabled={currentPage === 1}>Anterior</Button><span className="px-2">Página {currentPage} de {totalPages}</span><Button variant="outline" size="sm" onClick={() => setPage((value) => value + 1)} disabled={currentPage === totalPages}>Próxima</Button></div>}</div></CardContent></Card>;
}
